server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route cho orders-service của dự án VietMart
        - id: orders-service-route
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
