server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pham-anh-Hub/VietMart-Microservice-SS05-config-repo
          default-label: main